### PR TITLE
Added MyEdu Grade Distributions to Safari Version

### PR DESCRIPTION
**Pull request by kpavery**
The Safari version of the extension now gets grade distributions and average GPAs for courses from MyEdu.com. When a popup is opened for a specific professor and specific course, it gets the information for that specific pair. It doesn't get the information for the course overall or the professor overall; it's more specific.

It lists the average GPA for the course taught by that professor as text and embeds the image that shows the entire detailed distribution of grades.

**I didn't update the packaged version of the extension since it is signed with @connormulcahey's key.**

An example of how the popup looks with MyEdu information:

### CODE REVIEW

**Comment by kpavery** [comment]
Oh, and I also changed the permissions of a couple of the files since they were marked executable.

**Comment by cbarbello** [comment]
Holy crap Keith. Natasha and I were students in 160 last quarter. Thanks for contributing! We'll try to add this to the chrome version too! Unless you've already beat us lol

**Comment by kpavery** [comment]
I remember both of you. Nice job with the extension!

**Comment by connormulcahey** [comment]
This is so cool! I just updated the package. Thanks for fixing the permissions too!

**Comment by cbarbello** [comment]
Also Keith, we'll get your grade distribution added to chrome this weekend and push the update out (if you aren't already working on it yourself). Either way, I'll be sure to give you credit for it on the chrome store when it's done!

**Pull request merged**
